#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "cc -D_DARWIN_C_SOURCE -UOPENSSL_BN_ASM_PART_WORDS -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.1.sdk"
  #define PLATFORM "darwin-i386-cc"
  #define DATE "Thu May 10 17:52:35 PDT 2012"
#endif
