#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "cc -D_DARWIN_C_SOURCE -UOPENSSL_BN_ASM_PART_WORDS -arch armv7 -isysroot /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.0.sdk"
  #define PLATFORM "darwin-i386-cc"
  #define DATE "Mon Oct 31 11:59:47 PDT 2011"
#endif
