#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "cc -D_DARWIN_C_SOURCE -DOPENSSL_BN_ASM_PART_WORDS -arch i386 -isysroot /Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator5.0.sdk"
  #define PLATFORM "darwin-i386-cc"
  #define DATE "Sun Oct 23 00:40:22 PDT 2011"
#endif
